-- ACESSANDO O BD
USE DB_T04703_VINICIUS_SCARPIN;

-- CRIANDO A TABELA DE CONTATOS
CREATE TABLE CONTATOS (
ID int auto_increment primary key,
NOME VARCHAR(100),
TELEFONE varchar(20),
EMAIL VARCHAR(100),
DATA_NASCIMENTO DATE
);

-- INSERINDO REGISTROS NA TABELA DOS CONTATOS
INSERT INTO CONTATOS (NOME, TELEFONE, EMAIL, DATA_NASCIMENTO)
VALUES
('JOÃO', '14-99765-6543', 'JOÃOGABRIEL@GMAIL.COM', '2002-06-09'),
('KAREN', '13-99221-9893', 'KARENCORRÊA@GMAIL.COM', '2007-04-02'),
('LUCAS', '12-99934-7543', 'LUCASALMEIDA@GMAIL.COM', '1998-01-27'),
('GABRIEL', '11-99238-6095', 'GABRIELSILVA@GMAIL.COM', '1994-08-10');

-- SELECIONANDO A TABELA
SELECT * FROM CONTATOS;

-- INCLUIR UMA NOVA COLUNA NA TABELA DE CONTATOS
ALTER TABLE CONTATOS
ADD COLUMN ATIVO boolean default TRUE;

-- MODIFICANDO A QUANTIDADE DE CARACTERES NO VARCHAR DO NOME
ALTER TABLE CONTATOS
modify COLUMN NOME VARCHAR(150) NOT NULL;

-- ALTERAR O NOME DE UMA COLUNA NA TABELA CONTATOS
ALTER TABLE CONTATOS
CHANGE COLUMN TELEFONE CELULAR VARCHAR(20);

-- APAGANDO DA ESTRUTURA DA TABELA
ALTER TABLE CONTATOS
DROP COLUMN ATIVO;

