USE DB_T04703_VINICIUS_SCARPIN;

-- CRIANDO A TABELA DE GRUPOS
CREATE TABLE GRUPOS_CONTATOS (
ID_GRUPO INT AUTO_INCREMENT PRIMARY KEY,
GRUPO VARCHAR(100)
);

-- INSERINDO REGISTROS NA TABELA DE GRUPOS
INSERT INTO GRUPOS_CONTATOS (GRUPO)
VALUES
('FAMÍLIA'),
('TRABALHO'),
('AMIGOS');

-- CRIANDO A TABELA DE CONTATOS
CREATE TABLE TB_CONTATOS (
ID_CONTATO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100),
EMAIL VARCHAR(100),
ID_GRUPO INT NOT NULL,
FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS_CONTATOS (ID_GRUPO)
);

-- INSERINDO REGISTROS NA TABELA CONTATOS
INSERT INTO TB_CONTATOS (ID_GRUPO, NOME, EMAIL)
VALUES
(1,'DANIEL', 'DANIELALMEIDA@GMAIL.COM'),
(1,'LAURA', 'LAURAANTUNES@GMAIL.COM'),
(2,'SABRINA', 'SABRINADUARTE@GMAIL.COM'),
(3,'NEWTON', 'NEWTONLIMA@GMAIL.COM');

-- CRIANDO A TABELA DOS TELEFONES
CREATE TABLE TB_TELEFONE (
TELEFONE VARCHAR(20) PRIMARY KEY,
ID_CONTATO INT NOT NULL,
FOREIGN KEY (ID_CONTATO) REFERENCES TB_CONTATOS (ID_CONTATO)
);

-- INSERINDO REGISTROS NA TABELA TELEFONE
INSERT INTO TB_TELEFONE (ID_CONTATO, TELEFONE)
VALUES
(1, '14-99875-2755'),
(2, '11-99206-8872'),
(3, '12-97645-2265'),
(4, '13-99653-7032');


-- CONSULTA QUE IRÁ RETORNAR SOMENTE O NOME O CONTATO
SELECT NOME FROM TB_CONTATOS
ORDER BY NOME ASC;

-- CONSULTA AO CONTATO DANIEL
SELECT NOME, EMAIL, ID_GRUPO FROM TB_CONTATOS
WHERE NOME = 'DANIEL';


